---

chl_service_group: tuxedo
chl_service_group_id: 1010
chl_service_user_id_minimum: 1010
chl_service_uid_increment: 10
chl_service_users:
  - name: ceu
    uid:  "{{ chl_service_user_id_minimum + (0 * chl_service_uid_increment) | int }}"
  - name: chd
    uid:  "{{ chl_service_user_id_minimum + (1 * chl_service_uid_increment) | int }}"
  - name: ewf
    uid: "{{ chl_service_user_id_minimum + (2 * chl_service_uid_increment) | int }}"
  - name: xml
    uid: "{{ chl_service_user_id_minimum + (3 * chl_service_uid_increment) | int }}"

oracle_database_version: "10.2.0"
oracle_database_install_directory: "/opt/oracle/{{ oracle_database_version }}"

tuxedo_version: "8.1"
tuxedo_install_directory: "/opt/tuxedo/{{ tuxedo_version }}"
