---

tuxedo_service_group: tuxedo
tuxedo_service_group_id: 1010
tuxedo_service_user_id_minimum: 1010
tuxedo_service_user_id_increment: 10
tuxedo_service_users:
  - name: ceu
    uid:  "{{ tuxedo_service_user_id_minimum + (0 * tuxedo_service_user_id_increment) | int }}"
  - name: chd
    uid:  "{{ tuxedo_service_user_id_minimum + (1 * tuxedo_service_user_id_increment) | int }}"
  - name: ewf
    uid: "{{ tuxedo_service_user_id_minimum + (2 * tuxedo_service_user_id_increment) | int }}"
  - name: xml
    uid: "{{ tuxedo_service_user_id_minimum + (3 * tuxedo_service_user_id_increment) | int }}"

global_resource_limits:
  hard:
    nproc: 72703
    stack: unlimited
    msgqueue: 819200
  soft:
    nproc: 72703
    stack: 10240
    msgqueue: 819200

oracle_database_version: "10.2.0"
oracle_database_install_directory: "/opt/oracle/{{ oracle_database_version }}"

tuxedo_version: "8.1"
tuxedo_install_directory: "/opt/tuxedo/{{ tuxedo_version }}"
