---

- name: Determine UUID of swap volume
  ansible.builtin.shell:
    cmd: "blkid -s UUID -o value {{ swap_volume_device_node }}"
  register: swap_volume

- name: Add swap volume to filesystem table
  ansible.posix.mount:
    path: swap
    src: "UUID={{ swap_volume.stdout }}"
    fstype: swap
    opts: defaults
    state: present
